create table if not exists public."Crewmates" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  category text not null,
  color text not null,
  specialty text not null,
  speed integer not null check (speed between 1 and 5),
  stamina integer not null check (stamina between 1 and 5),
  bio text not null default ''
);

alter table public."Crewmates" enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'Crewmates'
      and policyname = 'Public can view crewmates'
  ) then
    create policy "Public can view crewmates"
      on public."Crewmates"
      for select
      to anon, authenticated
      using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'Crewmates'
      and policyname = 'Public can create crewmates'
  ) then
    create policy "Public can create crewmates"
      on public."Crewmates"
      for insert
      to anon, authenticated
      with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'Crewmates'
      and policyname = 'Public can update crewmates'
  ) then
    create policy "Public can update crewmates"
      on public."Crewmates"
      for update
      to anon, authenticated
      using (true)
      with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'Crewmates'
      and policyname = 'Public can delete crewmates'
  ) then
    create policy "Public can delete crewmates"
      on public."Crewmates"
      for delete
      to anon, authenticated
      using (true);
  end if;
end
$$;
